package sa.abrahman.zaxeg.core.port.in;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Currency;
import java.util.List;
import java.util.UUID;

import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import sa.abrahman.zaxeg.core.model.invoice.financial.MeasuringUnit;
import sa.abrahman.zaxeg.core.model.invoice.financial.PaymentMethod;
import sa.abrahman.zaxeg.core.model.invoice.financial.TaxCategory;
import sa.abrahman.zaxeg.core.model.invoice.meta.InvoiceDocumentType;
import sa.abrahman.zaxeg.core.model.invoice.meta.InvoiceSubtype;

@Getter
@Builder
public class InvoiceGenerationCommand {
    private String invoiceNumber;
    private UUID invoiceUuid;
    private LocalDate issueDate;
    private LocalTime issueTime;
    private LocalDate supplyDate;
    private PaymentMethod paymentMethod;
    private InvoiceSubtype invoiceSubtype;
    private InvoiceDocumentType invoiceDocumentType;
    private Currency documentCurrency;
    private PartyCommand supplier;
    private PartyCommand buyer;
    private List<LineCommand> lines;
    private BigDecimal prepaidAmount;
    private String issuanceReason;
    private BillingReferenceCommand billingReference;
    private List<InvoiceGlobalPayableCommand> documentAllowancesAndOrCharges;
    @Setter private FinancialsCommand financials;

    @Getter
    @Builder
    public static class PartyCommand {
        String registrationName;
        String vatNumber;
        String commercialRegistrationNumber;
        AddressCommand address;
    }

    @Getter
    @Builder
    public static class AddressCommand {
        private final String buildingNumber;
        private final String streetName;
        private final String district;
        private final String city;
        private final String postalCode;
        private final String additionalNumber;
    }

    @Getter
    @Builder
    public static class LineCommand {
        private final String identifier;
        private final String name;
        private final BigDecimal quantity;
        private final MeasuringUnit measuringUnit;
        private final BigDecimal unitPrice;
        private final BigDecimal lineDiscount;
        private final TaxCategory taxCategory;
        private final String exemptionReasonCode;
        private final String exemptionReasonText;
    }

    @Getter
    @Builder
    public static class BillingReferenceCommand {
        private final String originalInvoiceNumber;
    }

    @Getter
    @Builder
    public static class InvoiceGlobalPayableCommand {
        private final boolean isCharge;
        private final BigDecimal amount;
        private final String reason;
        private final TaxCategory taxCategory;
        private final String exemptionReasonCode;
        private final String exemptionReasonText;
    }

    @Getter
    @Builder
    public static class FinancialsCommand {
        @Builder.Default
        private final boolean autoGenerated = false;
        private final BigDecimal totalLineExtensionAmount;
        private final BigDecimal totalTaxAmount;
        private final BigDecimal totalTaxAmountInAccountingCurrency;
        private final BigDecimal totalAmountInclusive;
        private final BigDecimal prepaidAmount;
        private final BigDecimal payableAmount;
        private final BigDecimal taxExclusiveAmount;
    }
}
