package sa.abrahman.zaxeg.core.port.in;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Currency;
import java.util.List;
import java.util.UUID;

import lombok.Builder;
import lombok.Getter;
import sa.abrahman.zaxeg.core.model.invoice.financial.MeasuringUnit;
import sa.abrahman.zaxeg.core.model.invoice.financial.PaymentMethod;
import sa.abrahman.zaxeg.core.model.invoice.financial.TaxCategory;
import sa.abrahman.zaxeg.core.model.invoice.meta.InvoiceDocumentType;
import sa.abrahman.zaxeg.core.model.invoice.meta.InvoiceSubtype;

@Getter
@Builder
public class InvoiceGenerationPayload {
    private String invoiceNumber;
    private UUID invoiceUuid;
    private LocalDate issueDate;
    private LocalTime issueTime;
    private LocalDate supplyDate;
    private PaymentMethod paymentMethod;
    private InvoiceSubtype invoiceSubtype;
    private InvoiceDocumentType invoiceDocumentType;
    private Currency documentCurrency;
    private PartyPayload supplier;
    private PartyPayload buyer;
    private List<LinePayload> lines;
    private BigDecimal prepaidAmount;
    private String issuanceReason;
    private BillingReferencePayload billingReference;
    private List<InvoiceGlobalPayablePayload> documentAllowancesAndOrCharges;
    private FinancialsPayload financials;

    /**
     * immutable setter
     * @throws IllegalStateException if the financials has been mutated before
     */
    public void setFinancials(FinancialsPayload financials) {
        if (this.financials != null) {
            throw new IllegalStateException("Cannot mutate the payload financials");
        }
        this.financials = financials;
    }

    @Getter
    @Builder
    public static class PartyPayload {
        String registrationName;
        String vatNumber;
        String commercialRegistrationNumber;
        AddressPayload address;
    }

    @Getter
    @Builder
    public static class AddressPayload {
        private final String buildingNumber;
        private final String streetName;
        private final String district;
        private final String city;
        private final String postalCode;
        private final String additionalNumber;
    }

    @Getter
    @Builder
    public static class LinePayload {
        private final String identifier;
        private final String name;
        private final BigDecimal quantity;
        private final MeasuringUnit measuringUnit;
        private final BigDecimal unitPrice;
        private final BigDecimal lineDiscount;
        private final TaxCategory taxCategory;
        private final String exemptionReasonCode;
        private final String exemptionReasonText;
    }

    @Getter
    @Builder
    public static class BillingReferencePayload {
        private final String originalInvoiceNumber;
    }

    @Getter
    @Builder
    public static class InvoiceGlobalPayablePayload {
        private final boolean isCharge;
        private final BigDecimal amount;
        private final String reason;
        private final TaxCategory taxCategory;
        private final String exemptionReasonCode;
        private final String exemptionReasonText;
    }

    @Getter
    @Builder
    public static class FinancialsPayload {
        @Builder.Default
        private final boolean autoGenerated = false;
        private final BigDecimal totalLineExtensionAmount;
        private final BigDecimal totalTaxAmount;
        private final BigDecimal totalTaxAmountInAccountingCurrency;
        private final BigDecimal totalAmountInclusive;
        private final BigDecimal prepaidAmount;
        private final BigDecimal payableAmount;
        private final BigDecimal taxExclusiveAmount;
    }
}
