package sa.abrahman.zaxeg.core.service.processor;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.List;

import org.springframework.stereotype.Component;

import sa.abrahman.zaxeg.core.model.invoice.financial.TaxCategory;
import sa.abrahman.zaxeg.core.port.in.InvoiceGenerationPayload.FinancialsPayload;
import sa.abrahman.zaxeg.core.port.in.InvoiceGenerationPayload.InvoiceGlobalPayablePayload;
import sa.abrahman.zaxeg.core.port.in.InvoiceGenerationPayload.LinePayload;

@Component
public class FinancialsPayloadCalculator {
    public FinancialsPayload calculate(List<LinePayload> lines,
            List<InvoiceGlobalPayablePayload> allowancesAndOrCharges,
            BigDecimal prepaidAmount) {
        if (lines == null || lines.isEmpty()) {
            throw new IllegalStateException("Cannot calculate financials without invoice lines.");
        }

        BigDecimal totalExtension = BigDecimal.ZERO;
        BigDecimal totalLineTax = BigDecimal.ZERO;

        // Add lines
        for (LinePayload line : lines) {
            BigDecimal netPrice = calculateNetAmount(line.getQuantity(), line.getUnitPrice(), line.getLineDiscount());

            BigDecimal taxMultiplier = line.getTaxCategory().getRate().divide(new BigDecimal("100"), 2,
                    RoundingMode.HALF_UP);
            BigDecimal taxAmount = netPrice.multiply(taxMultiplier).setScale(2, RoundingMode.HALF_UP);

            totalExtension = totalExtension.add(netPrice);
            totalLineTax = totalLineTax.add(taxAmount);
        }

        // document allowances and charges
        BigDecimal totalDocAllowances = BigDecimal.ZERO;
        BigDecimal totalDocCharges = BigDecimal.ZERO;
        BigDecimal totalDocAllowanceTax = BigDecimal.ZERO;
        BigDecimal totalDocChargeTax = BigDecimal.ZERO;

        if (allowancesAndOrCharges != null) {
            for (InvoiceGlobalPayablePayload ac : allowancesAndOrCharges) {
                if (ac.isCharge()) {
                    totalDocCharges = totalDocCharges.add(ac.getAmount());
                    totalDocChargeTax = totalDocChargeTax.add(getTaxAmount(ac.getAmount(), ac.getTaxCategory()));
                } else {
                    totalDocAllowances = totalDocAllowances.add(ac.getAmount());
                    totalDocAllowanceTax = totalDocAllowanceTax.add(getTaxAmount(ac.getAmount(), ac.getTaxCategory()));
                }
            }
        }

        // Tax Exclusive = Lines - Allowances + Charges
        BigDecimal taxExclusiveAmount = totalExtension.subtract(totalDocAllowances).add(totalDocCharges);

        // Total Tax = Line Taxes - Allowance Taxes + Charge Taxes
        BigDecimal totalTaxAmount = totalLineTax.subtract(totalDocAllowanceTax).add(totalDocChargeTax);

        // Total Inclusive = Exclusive + Tax
        BigDecimal totalInclusive = taxExclusiveAmount.add(totalTaxAmount).setScale(2, RoundingMode.HALF_UP);

        BigDecimal safePrepaid = (prepaidAmount != null) ? prepaidAmount : BigDecimal.ZERO;
        BigDecimal payableAmount = totalInclusive.subtract(safePrepaid).setScale(2, RoundingMode.HALF_UP);

        return FinancialsPayload.builder()
                .autoGenerated(true)
                .totalLineExtensionAmount(totalExtension)
                .taxExclusiveAmount(taxExclusiveAmount)
                .totalTaxAmount(totalTaxAmount)
                .totalAmountInclusive(totalInclusive)
                .prepaidAmount(safePrepaid)
                .payableAmount(payableAmount)
                .build();
    }

    public BigDecimal calculateNetAmountForLine(LinePayload line) {
        return calculateNetAmount(line.getQuantity(), line.getUnitPrice(), line.getLineDiscount());
    }

    public static BigDecimal calculateNetAmount(BigDecimal quantity, BigDecimal unitPrice, BigDecimal lineDiscount) {
        if (quantity == null || unitPrice == null) return null;
        BigDecimal discount = lineDiscount == null ? BigDecimal.ZERO : lineDiscount;
        return quantity
                .multiply(unitPrice)
                .subtract(discount)
                .setScale(2, RoundingMode.HALF_UP);
    }

    public static BigDecimal getTaxAmount(BigDecimal amount, TaxCategory taxCategory) {
        if (amount == null || taxCategory == null)
            return BigDecimal.ZERO;
        // tax = amount * (rate / 100)
        return amount.multiply(taxCategory.getRate()).divide(new BigDecimal("100"), 2, RoundingMode.HALF_UP);
    }
}
